package docscomponents

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const generatedNotice = "<!-- Generated by docs-components; do not edit manually. -->"

// Generator creates reusable Markdown snippets from structured planning data.
type GeneratorOptions struct {
	GraphDirection string
	GraphClusters  bool
	GraphPalette   string
	PaletteFile    string
}

type Generator struct {
	repoRoot      string
	componentsDir string
	options       GeneratorOptions
	palettes      map[string]map[string]paletteColor
}

// NewGenerator creates a Generator configured to write component snippets for the repository at
// repoRoot. It resolves and stores absolute paths for repoRoot and componentsDir (defaulting
// componentsDir to repoRoot/docs/components when empty), ensures the components directory exists,
// loads the built-in palettes and merges palettes from options.PaletteFile if provided, and
// normalizes the supplied GeneratorOptions. Returns an initialized Generator or an error if input
// validation, path resolution, directory creation, or palette loading fails.
func NewGenerator(repoRoot, componentsDir string, options GeneratorOptions) (*Generator, error) {
	if repoRoot == "" {
		return nil, errors.New("repoRoot is required")
	}

	absRepoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve repo root: %w", err)
	}

	absComponentsDir := componentsDir
	if absComponentsDir == "" {
		absComponentsDir = filepath.Join(absRepoRoot, "docs", "components")
	}
	absComponentsDir, err = filepath.Abs(absComponentsDir)
	if err != nil {
		return nil, fmt.Errorf("resolve components dir: %w", err)
	}

	if err := os.MkdirAll(absComponentsDir, 0o755); err != nil {
		return nil, fmt.Errorf("ensure components dir: %w", err)
	}

	palettes := defaultPalettes()
	if options.PaletteFile != "" {
		palettePath := options.PaletteFile
		if !filepath.IsAbs(palettePath) {
			palettePath = filepath.Join(absRepoRoot, palettePath)
		}
		if err := mergePaletteFile(palettePath, palettes); err != nil {
			return nil, fmt.Errorf("load palette file: %w", err)
		}
	}

	options = normalizeOptions(options, palettes)

	return &Generator{repoRoot: absRepoRoot, componentsDir: absComponentsDir, options: options, palettes: palettes}, nil
}

// RepoRoot exposes the absolute repository root path used by the generator.
func (g *Generator) RepoRoot() string {
	return g.repoRoot
}

// ComponentsDir exposes the absolute components directory path.
func (g *Generator) ComponentsDir() string {
	return g.componentsDir
}

// Generate produces the default set of Markdown snippets.
func (g *Generator) Generate(ctx context.Context) error {
	roadmap, err := g.loadRoadmapArtifacts()
	if err != nil {
		return err
	}

	tasks, err := g.readTaskRecords(filepath.Join(g.repoRoot, "@hubless", "issues", "tasks"))
	if err != nil {
		return fmt.Errorf("load task records: %w", err)
	}

	if err := g.generateRoadmapTables(ctx, roadmap); err != nil {
		return err
	}

	if err := g.generateProgressOverview(ctx, roadmap, tasks); err != nil {
		return err
	}

	if err := g.generateDependencySummary(ctx, roadmap, tasks); err != nil {
		return err
	}

	if err := g.generateDependencyGraph(ctx, roadmap, tasks); err != nil {
		return err
	}

	if err := g.generateTaskTable(ctx, tasks); err != nil {
		return err
	}

	if err := g.generateTaskStatusSummary(ctx, tasks); err != nil {
		return err
	}

	if err := g.generateArchivedStories(ctx, roadmap); err != nil {
		return err
	}

	if err := g.generateArchivedTasks(ctx, tasks); err != nil {
		return err
	}

	if err := g.generateChangelog(ctx, tasks); err != nil {
		return err
	}

	return nil
}

type artifactRecord struct {
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Status       string   `json:"status"`
	Dependencies []string `json:"dependencies"`
}

type taskRecord struct {
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Status       string   `json:"status"`
	Owner        *string  `json:"owner"`
	Labels       []string `json:"labels"`
	Badges       []string `json:"badges"`
	UpdatedAt    *string  `json:"updated_at"`
	Dependencies []string `json:"dependencies"`
}

type roadmapArtifacts struct {
	Milestones []recordWithPath[artifactRecord]
	Features   []recordWithPath[artifactRecord]
	Stories    []recordWithPath[artifactRecord]
}

func (g *Generator) generateRoadmapTables(ctx context.Context, data roadmapArtifacts) error {
	tables := []struct {
		name           string
		records        []recordWithPath[artifactRecord]
		linkPrefix     string
		outputFilename string
	}{
		{
			name:           "milestones",
			records:        data.Milestones,
			linkPrefix:     "../milestones",
			outputFilename: "milestones-table.md",
		},
		{
			name:           "features",
			records:        data.Features,
			linkPrefix:     "../features",
			outputFilename: "features-table.md",
		},
		{
			name:           "stories",
			records:        data.Stories,
			linkPrefix:     "../../issues/stories",
			outputFilename: "stories-table.md",
		},
	}

	for _, table := range tables {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		builder := &strings.Builder{}
		builder.WriteString(generatedNotice)
		builder.WriteString("\n")
		builder.WriteString("| ID | Title | Status |\n")
		builder.WriteString("|----|-------|--------|\n")

		for _, record := range table.records {
			link := path.Join(table.linkPrefix, filepath.Base(record.sourcePath))
			fmt.Fprintf(builder, "| [%s](%s) | %s | %s |\n", record.data.ID, link, record.data.Title, record.data.Status)
		}

		outputPath := filepath.Join(g.componentsDir, "roadmap", table.outputFilename)
		if err := g.writeFile(outputPath, builder.String()); err != nil {
			return fmt.Errorf("write %s table: %w", table.name, err)
		}
	}

	return nil
}

func (g *Generator) generateProgressOverview(ctx context.Context, data roadmapArtifacts, tasks []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("| Artifact | Progress | Done | Total |\n")
	builder.WriteString("| --- | --- | --- | --- |\n")

	entries := []struct {
		label string
		done  int
		total int
	}{
		{
			label: "Milestones",
			done:  countDoneArtifacts(data.Milestones),
			total: len(data.Milestones),
		},
		{
			label: "Features",
			done:  countDoneArtifacts(data.Features),
			total: len(data.Features),
		},
		{
			label: "Stories",
			done:  countDoneArtifacts(data.Stories),
			total: len(data.Stories),
		},
		{
			label: "Tasks",
			done:  countDoneTasks(tasks),
			total: len(tasks),
		},
	}

	for _, entry := range entries {
		progress := renderProgressBar(entry.done, entry.total)
		fmt.Fprintf(builder, "| %s | %s | %d | %d |\n", entry.label, progress, entry.done, entry.total)
	}

	outputPath := filepath.Join(g.componentsDir, "roadmap", "progress.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write roadmap progress: %w", err)
	}

	return nil
}

func (g *Generator) generateDependencySummary(ctx context.Context, data roadmapArtifacts, tasks []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	sections := []struct {
		heading string
		rows    []dependencyRow
	}{
		{
			heading: "Milestones",
			rows:    dependencyRowsFromArtifacts(data.Milestones, "../milestones"),
		},
		{
			heading: "Features",
			rows:    dependencyRowsFromArtifacts(data.Features, "../features"),
		},
		{
			heading: "Stories",
			rows:    dependencyRowsFromArtifacts(data.Stories, "../../issues/stories"),
		},
		{
			heading: "Tasks",
			rows:    dependencyRowsFromTasks(tasks, "../../issues/tasks"),
		},
	}

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")

	for _, section := range sections {
		builder.WriteString("### " + section.heading + "\n\n")
		builder.WriteString("| ID | Depends On |\n")
		builder.WriteString("|----|-------------|\n")

		if len(section.rows) == 0 {
			builder.WriteString("| — | None recorded |\n\n")
			continue
		}

		for _, row := range section.rows {
			fmt.Fprintf(builder, "| [%s](%s) | %s |\n", row.id, row.link, formatList(row.deps))
		}
		builder.WriteString("\n")
	}

	outputPath := filepath.Join(g.componentsDir, "roadmap", "dependencies.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write dependencies summary: %w", err)
	}

	return nil
}

func (g *Generator) generateDependencyGraph(ctx context.Context, data roadmapArtifacts, tasks []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	var all []typedRecord

	for _, record := range data.Milestones {
		all = append(all, typedRecord{
			id:        record.data.ID,
			title:     record.data.Title,
			typeLabel: "Milestone",
			deps:      cleanValues(record.data.Dependencies),
		})
	}
	for _, record := range data.Features {
		all = append(all, typedRecord{
			id:        record.data.ID,
			title:     record.data.Title,
			typeLabel: "Feature",
			deps:      cleanValues(record.data.Dependencies),
		})
	}
	for _, record := range data.Stories {
		all = append(all, typedRecord{
			id:        record.data.ID,
			title:     record.data.Title,
			typeLabel: "Story",
			deps:      cleanValues(record.data.Dependencies),
		})
	}
	for _, record := range tasks {
		all = append(all, typedRecord{
			id:        record.data.ID,
			title:     record.data.Title,
			typeLabel: "Task",
			deps:      cleanValues(record.data.Dependencies),
		})
	}

	nodeIDs := map[string]string{}
	labels := map[string]string{}
	seenIDs := map[string]string{}

	for idx, record := range all {
		if record.id == "" {
			continue
		}
		if previousType, ok := seenIDs[record.id]; ok {
			return fmt.Errorf("duplicate dependency graph id %q in %s and %s records", record.id, previousType, record.typeLabel)
		}
		seenIDs[record.id] = record.typeLabel
		nodeName := fmt.Sprintf("n%d", idx)
		nodeIDs[record.id] = nodeName
		labels[nodeName] = escapeMermaidLabel(fmt.Sprintf("%s\\n%s", record.typeLabel, record.title))
	}

	edges := make([][2]string, 0)
	for _, record := range all {
		src, ok := nodeIDs[record.id]
		if !ok {
			continue
		}
		for _, dep := range record.deps {
			if dst, ok := nodeIDs[dep]; ok {
				edges = append(edges, [2]string{src, dst})
			}
		}
	}

	direction := strings.ToUpper(strings.TrimSpace(g.options.GraphDirection))
	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("```mermaid\n")
	builder.WriteString(fmt.Sprintf("graph %s\n", direction))

	nodeNames := make([]string, 0, len(labels))
	for node := range labels {
		nodeNames = append(nodeNames, node)
	}
	sort.Strings(nodeNames)

	for _, node := range nodeNames {
		label := labels[node]
		fmt.Fprintf(builder, "    %s[\"%s\"]\n", node, label)
	}

	palette := g.palettes[g.options.GraphPalette]
	if palette == nil {
		palette = g.palettes["evergreen"]
	}
	classNames := make([]string, 0, len(palette))
	for className := range palette {
		classNames = append(classNames, className)
	}
	sort.Strings(classNames)
	for _, className := range classNames {
		color := palette[className]
		fmt.Fprintf(builder, "    classDef %s fill:%s,stroke:%s,color:%s,stroke-width:1px;\n", className, color.Fill, color.Stroke, color.Text)
	}

	if g.options.GraphClusters {
		for _, cluster := range orderedTypes {
			nodes := collectNodesByType(cluster, all, nodeIDs)
			if len(nodes) == 0 {
				continue
			}
			fmt.Fprintf(builder, "    subgraph %s\n", cluster)
			fmt.Fprintf(builder, "        direction %s\n", direction)
			for _, node := range nodes {
				fmt.Fprintf(builder, "        %s\n", node)
			}
			builder.WriteString("    end\n")
		}
	}

	classAssignments := make(map[string]string)
	for _, record := range all {
		if node, ok := nodeIDs[record.id]; ok {
			className := strings.ToLower(record.typeLabel)
			if _, ok := palette[className]; ok {
				classAssignments[node] = className
			}
		}
	}

	assignmentNodes := make([]string, 0, len(classAssignments))
	for node := range classAssignments {
		assignmentNodes = append(assignmentNodes, node)
	}
	sort.Strings(assignmentNodes)
	for _, node := range assignmentNodes {
		fmt.Fprintf(builder, "    class %s %s;\n", node, classAssignments[node])
	}

	for _, edge := range edges {
		fmt.Fprintf(builder, "    %s --> %s\n", edge[0], edge[1])
	}

	builder.WriteString("```\n")

	outputPath := filepath.Join(g.componentsDir, "roadmap", "dependencies-graph.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write dependency graph: %w", err)
	}

	return nil
}

func (g *Generator) generateTaskTable(ctx context.Context, records []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("| ID | Title | Status | Owner | Labels | Badges | Updated |\n")
	builder.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")

	for _, record := range records {
		owner := "_unassigned_"
		if record.data.Owner != nil && strings.TrimSpace(*record.data.Owner) != "" {
			owner = *record.data.Owner
		}

		labels := formatList(record.data.Labels)
		badges := formatList(record.data.Badges)
		if labels == "—" {
			labels = ""
		}
		if badges == "—" {
			badges = ""
		}

		updated := "—"
		if record.data.UpdatedAt != nil && strings.TrimSpace(*record.data.UpdatedAt) != "" {
			updated = *record.data.UpdatedAt
		}

		link := path.Join("../tasks", filepath.Base(record.sourcePath))
		fmt.Fprintf(
			builder,
			"| [%s](%s) | %s | %s | %s | %s | %s | %s |\n",
			record.data.ID,
			link,
			record.data.Title,
			record.data.Status,
			owner,
			labels,
			badges,
			updated,
		)
	}

	outputPath := filepath.Join(g.componentsDir, "issues", "tasks-table.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write tasks table: %w", err)
	}

	return nil
}

func (g *Generator) generateTaskStatusSummary(ctx context.Context, records []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	counts := map[string]int{}
	for _, record := range records {
		status := strings.TrimSpace(record.data.Status)
		if status == "" {
			status = "UNKNOWN"
		}
		counts[status]++
	}

	statuses := make([]string, 0, len(counts))
	for status := range counts {
		statuses = append(statuses, status)
	}

	sort.Slice(statuses, func(i, j int) bool {
		ri := statusRank(statuses[i])
		rj := statusRank(statuses[j])
		if ri != rj {
			return ri < rj
		}
		return strings.ToLower(statuses[i]) < strings.ToLower(statuses[j])
	})

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("| Status | Count |\n")
	builder.WriteString("| --- | --- |\n")

	for _, status := range statuses {
		fmt.Fprintf(builder, "| %s | %d |\n", status, counts[status])
	}

	outputPath := filepath.Join(g.componentsDir, "issues", "status-summary.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write task status summary: %w", err)
	}

	return nil
}

func (g *Generator) generateArchivedStories(ctx context.Context, data roadmapArtifacts) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	rows := make([]recordWithPath[artifactRecord], 0)
	for _, record := range data.Stories {
		if isDoneStatus(record.data.Status) {
			rows = append(rows, record)
		}
	}

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("| ID | Title | Completed Status |\n")
	builder.WriteString("| --- | --- | --- |\n")

	if len(rows) == 0 {
		builder.WriteString("| — | — | — |\n")
	} else {
		for _, record := range rows {
			fmt.Fprintf(builder, "| %s | %s | %s |\n", record.data.ID, record.data.Title, record.data.Status)
		}
	}

	outputPath := filepath.Join(g.componentsDir, "issues", "archived-stories.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write archived stories: %w", err)
	}

	return nil
}

func (g *Generator) generateArchivedTasks(ctx context.Context, records []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	rows := make([]recordWithPath[taskRecord], 0)
	for _, record := range records {
		if isDoneStatus(record.data.Status) {
			rows = append(rows, record)
		}
	}

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")
	builder.WriteString("| ID | Title | Completed On | Badges |\n")
	builder.WriteString("| --- | --- | --- | --- |\n")

	if len(rows) == 0 {
		builder.WriteString("| — | — | — | — |\n")
	} else {
		for _, record := range rows {
			completed := "—"
			if record.data.UpdatedAt != nil && strings.TrimSpace(*record.data.UpdatedAt) != "" {
				completed = *record.data.UpdatedAt
			}
			fmt.Fprintf(
				builder,
				"| %s | %s | %s | %s |\n",
				record.data.ID,
				record.data.Title,
				completed,
				formatList(record.data.Badges),
			)
		}
	}

	outputPath := filepath.Join(g.componentsDir, "issues", "archived-tasks.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write archived tasks: %w", err)
	}

	return nil
}

type dependencyRow struct {
	id   string
	link string
	deps []string
}

type typedRecord struct {
	id        string
	title     string
	typeLabel string
	deps      []string
}

type recordWithPath[T any] struct {
	sourcePath string
	data       T
}

func (g *Generator) loadRoadmapArtifacts() (roadmapArtifacts, error) {
	var result roadmapArtifacts

	milestones, err := g.readArtifactRecords(filepath.Join(g.repoRoot, "@hubless", "roadmap", "milestones"))
	if err != nil {
		return result, fmt.Errorf("load milestones: %w", err)
	}

	features, err := g.readArtifactRecords(filepath.Join(g.repoRoot, "@hubless", "roadmap", "features"))
	if err != nil {
		return result, fmt.Errorf("load features: %w", err)
	}

	stories, err := g.readArtifactRecords(filepath.Join(g.repoRoot, "@hubless", "issues", "stories"))
	if err != nil {
		return result, fmt.Errorf("load stories: %w", err)
	}

	result.Milestones = milestones
	result.Features = features
	result.Stories = stories

	return result, nil
}

func (g *Generator) readArtifactRecords(dir string) ([]recordWithPath[artifactRecord], error) {
	if _, err := os.Stat(dir); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}

	files, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}

	if len(files) == 0 {
		return nil, nil
	}

	sort.Strings(files)

	results := make([]recordWithPath[artifactRecord], 0, len(files))
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", file, err)
		}

		var record artifactRecord
		if err := json.Unmarshal(data, &record); err != nil {
			return nil, fmt.Errorf("decode %s: %w", file, err)
		}

		if record.ID == "" || record.Title == "" || record.Status == "" {
			return nil, fmt.Errorf("record %s missing required fields", file)
		}

		results = append(results, recordWithPath[artifactRecord]{sourcePath: file, data: record})
	}

	return results, nil
}

func (g *Generator) readTaskRecords(dir string) ([]recordWithPath[taskRecord], error) {
	if _, err := os.Stat(dir); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}

	files, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}

	if len(files) == 0 {
		return nil, nil
	}

	sort.Strings(files)

	results := make([]recordWithPath[taskRecord], 0, len(files))
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", file, err)
		}

		var record taskRecord
		if err := json.Unmarshal(data, &record); err != nil {
			return nil, fmt.Errorf("decode %s: %w", file, err)
		}

		if record.ID == "" || record.Title == "" || record.Status == "" {
			return nil, fmt.Errorf("task %s missing required fields", file)
		}

		results = append(results, recordWithPath[taskRecord]{sourcePath: file, data: record})
	}

	return results, nil
}

// dependencyRowsFromArtifacts builds dependency rows for artifacts.
// It examines each artifact record, cleans its Dependencies with cleanValues,
// and for records that have one or more dependencies appends a dependencyRow
// containing the artifact ID, a link formed by joining linkPrefix with the
// basename of the record's sourcePath, and the cleaned dependency list.
// Records without dependencies are omitted from the returned slice.
func dependencyRowsFromArtifacts(records []recordWithPath[artifactRecord], linkPrefix string) []dependencyRow {
	rows := make([]dependencyRow, 0, len(records))
	for _, record := range records {
		deps := cleanValues(record.data.Dependencies)
		if len(deps) == 0 {
			continue
		}
		rows = append(rows, dependencyRow{
			id:   record.data.ID,
			link: path.Join(linkPrefix, filepath.Base(record.sourcePath)),
			deps: deps,
		})
	}

	return rows
}

// dependencyRowsFromTasks builds dependencyRow entries for each task record that has
// one or more dependencies. The returned rows contain the task ID, a link formed by
// joining linkPrefix with the task record's source file base name, and the cleaned
// list of dependency IDs. Records without dependencies are omitted.
func dependencyRowsFromTasks(records []recordWithPath[taskRecord], linkPrefix string) []dependencyRow {
	rows := make([]dependencyRow, 0)
	for _, record := range records {
		deps := cleanValues(record.data.Dependencies)
		if len(deps) == 0 {
			continue
		}
		rows = append(rows, dependencyRow{
			id:   record.data.ID,
			link: path.Join(linkPrefix, filepath.Base(record.sourcePath)),
			deps: deps,
		})
	}

	return rows
}

// countDoneArtifacts returns the number of artifact records whose Status is considered completed.
// It uses isDoneStatus to determine completion (e.g., DONE, COMPLETED, COMPLETE, SHIPPED, case-insensitive).
func countDoneArtifacts(records []recordWithPath[artifactRecord]) int {
	count := 0
	for _, record := range records {
		if isDoneStatus(record.data.Status) {
			count++
		}
	}
	return count
}

// (e.g., DONE, COMPLETED, COMPLETE, SHIPPED).
func countDoneTasks(records []recordWithPath[taskRecord]) int {
	count := 0
	for _, record := range records {
		if isDoneStatus(record.data.Status) {
			count++
		}
	}
	return count
}

type paletteColor struct {
	Fill   string
	Stroke string
	Text   string
}

// defaultPalettes returns the built-in color palettes used for graph node styling.
//
// The return value is a map from palette name to a map of class names
// ("milestone", "feature", "story", "task") to paletteColor. The function
// returns a deep copy of the internal base definitions so callers can modify
// the result without affecting the originals.
func defaultPalettes() map[string]map[string]paletteColor {
	base := map[string]map[string]paletteColor{
		"evergreen": {
			"milestone": {Fill: "#2C5F2D", Stroke: "#C86E3B", Text: "#F4F1E8"},
			"feature":   {Fill: "#6B9F7F", Stroke: "#2C5F2D", Text: "#F4F1E8"},
			"story":     {Fill: "#E9B872", Stroke: "#C86E3B", Text: "#0E1111"},
			"task":      {Fill: "#C86E3B", Stroke: "#2C5F2D", Text: "#F4F1E8"},
		},
		"infrared": {
			"milestone": {Fill: "#1A1C23", Stroke: "#FF2A6D", Text: "#B9C1D6"},
			"feature":   {Fill: "#6C63FF", Stroke: "#27F0C7", Text: "#FFFFFF"},
			"story":     {Fill: "#0A0B0F", Stroke: "#FF2A6D", Text: "#FFFFFF"},
			"task":      {Fill: "#27F0C7", Stroke: "#6C63FF", Text: "#0A0B0F"},
		},
		"zerothrow": {
			"milestone": {Fill: "#141820", Stroke: "#10B9D8", Text: "#D8DEE9"},
			"feature":   {Fill: "#0D0F12", Stroke: "#64D6E8", Text: "#D8DEE9"},
			"story":     {Fill: "#10B9D8", Stroke: "#A3E635", Text: "#0D0F12"},
			"task":      {Fill: "#A3E635", Stroke: "#10B9D8", Text: "#0D0F12"},
		},
	}

	cloned := make(map[string]map[string]paletteColor, len(base))
	for name, classes := range base {
		copyClasses := make(map[string]paletteColor, len(classes))
		for className, color := range classes {
			copyClasses[className] = color
		}
		cloned[name] = copyClasses
	}
	return cloned
}

type rawPaletteColor struct {
	Fill   string `json:"fill"`
	Stroke string `json:"stroke"`
	Text   string `json:"text"`
}

// mergePaletteFile reads a JSON palette file at path and merges its palette
// definitions into the provided palettes map.
//
// The file may contain multiple palette objects keyed by name; a top-level
// "$schema" key is ignored. Palette and class names are normalized to lower
// case and trimmed. Each palette class must be one of the known classes
// (milestone, feature, story, task) and must include non-empty `fill`,
// `stroke`, and `text` color values. Missing file is not an error (returns
// nil). On success the palettes map is mutated to include or update the
// palettes from the file; on failure a descriptive error is returned.
func mergePaletteFile(path string, palettes map[string]map[string]paletteColor) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}

	var fileData map[string]json.RawMessage
	if err := json.Unmarshal(data, &fileData); err != nil {
		return fmt.Errorf("parse palette file: %w", err)
	}

	for paletteName, payload := range fileData {
		if paletteName == "$schema" {
			continue
		}
		name := strings.ToLower(strings.TrimSpace(paletteName))
		if name == "" {
			return fmt.Errorf("palette name cannot be empty")
		}
		existing := palettes[name]
		if existing == nil {
			existing = make(map[string]paletteColor)
			palettes[name] = existing
		}
		var classes map[string]rawPaletteColor
		if err := json.Unmarshal(payload, &classes); err != nil {
			return fmt.Errorf("parse palette %q: %w", paletteName, err)
		}
		for className, color := range classes {
			key := strings.ToLower(strings.TrimSpace(className))
			if !isKnownPaletteClass(key) {
				return fmt.Errorf("unknown palette class %q in palette %q", className, paletteName)
			}
			if strings.TrimSpace(color.Fill) == "" || strings.TrimSpace(color.Stroke) == "" || strings.TrimSpace(color.Text) == "" {
				return fmt.Errorf("palette %q class %q must include fill, stroke, and text colors", paletteName, className)
			}
			existing[key] = paletteColor{
				Fill:   color.Fill,
				Stroke: color.Stroke,
				Text:   color.Text,
			}
		}
	}

	return nil
}

// renderProgressBar returns a fixed-width textual progress bar (10 units) and a
// percentage for the given done/total pair.
//
// If total is <= 0 the function returns a zeroed bar "[----------] 0%". The
// progress ratio is clamped to [0,1]; the number of filled units is computed by
// rounding ratio*10 and the percentage is ratio*100 rounded to the nearest
// integer.
func renderProgressBar(done, total int) string {
	const width = 10
	if total <= 0 {
		return "[----------] 0%"
	}

	ratio := float64(done) / float64(total)
	if ratio < 0 {
		ratio = 0
	}
	if ratio > 1 {
		ratio = 1
	}

	filled := int(math.Round(ratio * width))
	if filled > width {
		filled = width
	}

	percent := int(math.Round(ratio * 100))
	return fmt.Sprintf("[%s%s] %d%%", strings.Repeat("#", filled), strings.Repeat("-", width-filled), percent)
}

// isDoneStatus reports whether a status string represents a completed state.
// It returns true for the case-insensitive values "DONE", "COMPLETED", "COMPLETE", or "SHIPPED"; otherwise false.
func isDoneStatus(status string) bool {
	switch strings.ToUpper(strings.TrimSpace(status)) {
	case "DONE", "COMPLETED", "COMPLETE", "SHIPPED":
		return true
	default:
		return false
	}
}

// any other or empty status            -> 5
func statusRank(status string) int {
	switch strings.ToUpper(strings.TrimSpace(status)) {
	case "DONE", "COMPLETED", "COMPLETE", "SHIPPED":
		return 0
	case "IN_PROGRESS":
		return 1
	case "STARTED":
		return 2
	case "BLOCKED":
		return 3
	case "PLANNED":
		return 4
	default:
		return 5
	}
}

// cleanValues returns a new slice containing the non-empty strings from values
// after trimming surrounding whitespace. The original order is preserved.
// If values is nil or has length zero, cleanValues returns nil.
func cleanValues(values []string) []string {
	if len(values) == 0 {
		return nil
	}

	cleaned := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		cleaned = append(cleaned, trimmed)
	}

	return cleaned
}

func (g *Generator) generateChangelog(ctx context.Context, records []recordWithPath[taskRecord]) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	done := make([]recordWithPath[taskRecord], 0)
	for _, record := range records {
		if isDoneStatus(record.data.Status) {
			done = append(done, record)
		}
	}

	sort.Slice(done, func(i, j int) bool {
		ti := parseTimestamp(derefString(done[i].data.UpdatedAt))
		tj := parseTimestamp(derefString(done[j].data.UpdatedAt))
		if !ti.Equal(tj) {
			return ti.After(tj)
		}
		return done[i].data.ID < done[j].data.ID
	})

	builder := &strings.Builder{}
	builder.WriteString(generatedNotice)
	builder.WriteString("\n")

	if len(done) == 0 {
		builder.WriteString("_No completed tasks yet._\n")
	} else {
		sort.Slice(done, func(i, j int) bool {
			ti := parseTimestamp(derefString(done[i].data.UpdatedAt))
			tj := parseTimestamp(derefString(done[j].data.UpdatedAt))
			if !ti.Equal(tj) {
				return ti.After(tj)
			}
			return done[i].data.ID < done[j].data.ID
		})

		for _, record := range done {
			date := derefString(record.data.UpdatedAt)
			if strings.TrimSpace(date) == "" {
				date = "—"
			}
			badges := formatList(record.data.Badges)
			if badges == "—" {
				badges = ""
			} else {
				badges = " — " + badges
			}
			fmt.Fprintf(
				builder,
				"- %s — **%s** (%s)%s\n",
				date,
				record.data.Title,
				record.data.ID,
				badges,
			)
		}
	}

	outputPath := filepath.Join(g.componentsDir, "issues", "changelog.md")
	if err := g.writeFile(outputPath, builder.String()); err != nil {
		return fmt.Errorf("write changelog snippet: %w", err)
	}

	return nil
}

func parseTimestamp(s string) time.Time {
	s = strings.TrimSpace(s)
	if s == "" {
		return time.Time{}
	}
	// Try common formats (include non-padded and zero-padded forms)
	layouts := []string{
		time.RFC3339,
		"2006-1-2 15:04:05",
		"2006-1-2 15:04",
		"2006-1-2",
		"2006-01-02 15:04:05",
		"2006-01-02 15:04",
		"2006-01-02",
	}
	for _, layout := range layouts {
		if t, err := time.Parse(layout, s); err == nil {
			return t
		}
	}
	// Fallback: normalize YYYY-M-D by parsing numeric month/day and zero-padding
	parts := strings.Split(s, "-")
	if len(parts) == 3 {
		y := strings.TrimSpace(parts[0])
		mStr := strings.TrimSpace(parts[1])
		dStr := strings.TrimSpace(parts[2])
		if mi, err1 := strconv.Atoi(mStr); err1 == nil {
			if di, err2 := strconv.Atoi(dStr); err2 == nil {
				if t, err := time.Parse("2006-01-02", fmt.Sprintf("%s-%02d-%02d", y, mi, di)); err == nil {
					return t
				}
			}
		}
	}
	return time.Time{}
}

func (g *Generator) writeFile(destPath, contents string) error {
	if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
		return fmt.Errorf("ensure directory for %s: %w", destPath, err)
	}

	return os.WriteFile(destPath, []byte(contents), 0o644)
}

// formatList trims and filters empty strings from values and returns them joined by ", ".
// If the resulting list is empty it returns an em dash "—".
func formatList(values []string) string {
	cleaned := cleanValues(values)
	if len(cleaned) == 0 {
		return "—"
	}

	return strings.Join(cleaned, ", ")
}

// escapeMermaidLabel returns label with characters escaped for use in Mermaid diagrams.
// It escapes backslashes, double quotes, and square brackets so the label can be safely
// embedded in Mermaid node definitions.
func escapeMermaidLabel(label string) string {
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		"\"", "\\\"",
		"[", "\\[",
		"]", "\\]",
	)
	return replacer.Replace(label)
}

// the record's id; records without a corresponding entry in nodeIDs are skipped.
func collectNodesByType(typeLabel string, records []typedRecord, nodeIDs map[string]string) []string {
	nodes := make([]string, 0)
	for _, record := range records {
		if record.typeLabel != typeLabel {
			continue
		}
		if node, ok := nodeIDs[record.id]; ok {
			nodes = append(nodes, node)
		}
	}

	sort.Strings(nodes)
	return nodes
}

// normalizeOptions normalizes and validates graph-related fields in a GeneratorOptions value.
// It uppercases and validates GraphDirection (defaults to "LR" if invalid) and lowercases
// GraphPalette (defaults to "evergreen" or to "evergreen" if the named palette is not present
// in the provided palettes map), returning the adjusted options.
func normalizeOptions(options GeneratorOptions, palettes map[string]map[string]paletteColor) GeneratorOptions {
	direction := strings.ToUpper(strings.TrimSpace(options.GraphDirection))
	if !isValidDirection(direction) {
		direction = "LR"
	}
	options.GraphDirection = direction

	palette := strings.ToLower(strings.TrimSpace(options.GraphPalette))
	if palette == "" {
		palette = "evergreen"
	}
	if _, ok := palettes[palette]; !ok {
		palette = "evergreen"
	}
	options.GraphPalette = palette

	return options
}

// isValidDirection reports whether the given graph direction is one of the
// supported Mermaid directions: "LR", "RL", "TB", or "BT".
func isValidDirection(direction string) bool {
	switch direction {
	case "LR", "RL", "TB", "BT":
		return true
	default:
		return false
	}
}

var orderedTypes = []string{"Milestone", "Feature", "Story", "Task"}

// string if the pointer is nil.
func derefString(value *string) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(*value)
}

// isKnownPaletteClass reports whether the given class name is a recognized palette
// class. Valid names are "milestone", "feature", "story", and "task".
func isKnownPaletteClass(class string) bool {
	switch class {
	case "milestone", "feature", "story", "task":
		return true
	default:
		return false
	}
}
